spring.application.name=kialo-assistant
openai.key=${OPENAI_API_KEY}
server.port=8082

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:1234/termit/sluzby/auth/realms/termit
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://auth-server:8080/realms/termit/protocol/openid-connect/certs

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:never}
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update